#use_frameworks!

platform :ios, '8.0'

target 'Login_Project_Example' do
  pod 'Login_Project', :path => '../'
  
  pod 'CTMediator', :path => '../../CTMediator'
  pod 'Mediator_Main', :path => '../../Mediator_Main'

  target 'Login_Project_Tests' do
    inherit! :search_paths

    
  end
end
