#use_frameworks!

platform :ios, '8.0'

target 'Mediator_Login_Example' do
  
  pod 'CTMediator', :path => '../../CTMediator'
  
  pod 'Mediator_Login', :path => '../'

  pod 'Login_Project', :path => '../../Login_Project'
  
  target 'Mediator_Login_Tests' do
    inherit! :search_paths

    
  end
end
